artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Mehulsaini80/DeepLearningproject/raw/refs/heads/main/Chicken-fecal-images.zip
  unzip_dir: artifacts/data_ingestion 
  local_data_file: artifacts/data_ingestion/data.zip